dataset_path: /home/notebook/code/sharedGroup/rg-image-edit/xuekaiwen/mask_diffusion/nanoMDM/outputs/benchmark/local_datasets/MME_local
dataset_kwargs:
  token: True
task: "mme_fast280"
test_split: test
process_docs: !function utils.mme_process_docs_fast280
output_type: generate_until
doc_to_visual: !function utils.mme_doc_to_visual
doc_to_text: !function utils.mme_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 4
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.mme_process_results
metric_list:
  - metric: mme_total_score
    aggregation: !function utils.mme_aggregate_results
    higher_is_better: true
  - metric: mme_perception_score
    aggregation: !function utils.mme_aggregate_results
    higher_is_better: true
  - metric: mme_cognition_score
    aggregation: !function utils.mme_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
  gpt4v:
    pre_prompt: ""
    post_prompt: "\nAnswer the question with Yes or No."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
  otterhd:
    pre_prompt: ""
    post_prompt: " Answer:"
  xcomposer2_4khd:
    pre_prompt: "[UNUSED_TOKEN_146]user\n"
    post_prompt: " Answer this question briefly[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n"
  plm:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0
