CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
# IMAGE_TOKEN_INDEX = -200

DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IM_START_TOKEN = "[IMG]"
DEFAULT_IM_END_TOKEN = "[/IMG]"


# IMAGE_TOKEN_IDX = 32002
# DEFAULT_IM_START_TOKEN_IDX = 32000
# DEFAULT_IM_END_TOKEN_IDX = 32001

IMAGE_TOKEN_IDX = 151655
DEFAULT_IM_START_TOKEN_IDX = 151669
DEFAULT_IM_END_TOKEN_IDX = 151670
UND_IMAGE_TOKEN_IDX = 151671
# N_QUERY = 729


# IN TOKENIZER 
# IMAGE_TOKEN_IDX = 151671  ->  <image>
# DEFAULT_IM_START_TOKEN_IDX = 151669 -> [IMG]
# DEFAULT_IM_END_TOKEN_IDX = 151670 -> [/IMG]
# UND_IMAGE_TOKEN_IDX = ??? -> ???

DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
