CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200

DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IM_START_TOKEN = "[IMG]"
DEFAULT_IM_END_TOKEN = "[/IMG]"

DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN_LLADA = "<im_start>"
DEFAULT_IM_END_TOKEN_LLADA = "<im_end>"

IMAGE_TOKEN_IDX_LLADA = 126351
DEFAULT_IM_START_TOKEN_IDX_LLADA = 126349

# IMAGE_TOKEN_IDX = 32002
# DEFAULT_IM_START_TOKEN_IDX = 32000
# DEFAULT_IM_END_TOKEN_IDX = 32001

IMAGE_TOKEN_IDX = 151667
DEFAULT_IM_START_TOKEN_IDX = 128257
DEFAULT_IM_END_TOKEN_IDX = 128258
UND_IMAGE_TOKEN_IDX = 151655
# N_QUERY = 729

# IN TOKENIZER 
# IMAGE_TOKEN_IDX = 151671  ->  <image>
# DEFAULT_IM_START_TOKEN_IDX = 151669 -> [IMG]
# DEFAULT_IM_END_TOKEN_IDX = 151670 -> [/IMG]
# UND_IMAGE_TOKEN_IDX = ??? -> ???


IMAGE_PLACEHOLDER = "<image-placeholder>"
